### ISSUE TITLE
climate size interactions

### ISSUE THREAD

**Issue by atredennick** [atredennick/MicroMesoForecast#16]
Need to check effect of adding an offset to `log(area.t0)` like `log(area.t0) + 2` so that climate by size interactions are easier to interpret. Run both versions in GLM framework and look for differences in statistical metrics (F and t values).

**Comment by atredennick** [comment]
Also need to add these interactions into the IPM vital rate functions and set up structure to be fed into those functions.

**Comment by atredennick** [comment]
Here's a snippet from Peter's code with sizeXclimate interactions:

`G=function(v,u,W,Gpars,weather,doYear,doSpp){
  mu=Gpars$intcpt[doSpp]+Gpars$intcpt.yr[doYear,doSpp]+(Gpars$slope[doSpp]+Gpars$slope.yr[doYear,doSpp])*u+
     sum(Gpars$clim[doSpp,]*weather)+sum(Gpars$slopeXclim[doSpp,]*weather)*u+
     W%*%(Gpars$nb[doSpp,])`

Build on this and then have Peter check.

**Comment by atredennick** [comment]
OK, I've got a working version (see c8028f0) with growth and survival functions that look like this:

`mu <- Gpars$intcpt[doSpp]+                    # intercept`
       ` Gpars$intG[doSpp]+                      # group offset`
       ` Gpars$slope[doSpp]*u+                   # size effect (slope)`
       ` W*Gpars$nb[doSpp]+                      # crowding effect`
        `(W*Gpars$nbXsize)*u+                    # size-crowding interaction`
        `sum(Gpars$clim[doSpp,]*climate)+        # main climate effects`
       ` sum(Gpars$slopeXclim[doSpp,]*climate[1:5])*u # climate-size interaction effects`

@pbadler Does this look good/right to you? 
Specifically the interactions between climate and size:
 ` sum(Gpars$slopeXclim[doSpp,]*climate[1:5])*u`

and the interaction between climate and crowding:
 `(W*Gpars$nbXsize)*u`

**Comment by pbadler** [comment]
That does NOT look right to me. I think it should be:
|sum(Gpars$slopeXclim[doSpp,]*climate[1:5]*u|)

You multiply size by climate before summing.

On 5/16/2015 3:58 PM, Andrew Tredennick wrote:
>
> OK, I've got a working version (see c8028f0 
> <https://github.com/atredennick/MicroMesoForecast/commit/c8028f040c192aada9ffbe144d17b6cf7124b678>) 
> with growth and survival functions that look like this:
>
> |mu <- Gpars$intcpt[doSpp]+ # intercept|
> |Gpars$intG[doSpp]+ # group offset|
> |Gpars$slope[doSpp]*u+ # size effect (slope)|
> |W*Gpars$nb[doSpp]+ # crowding effect|
> |(W*Gpars$nbXsize)*u+ # size-crowding interaction|
> |sum(Gpars$clim[doSpp,]*climate)+ # main climate effects|
> |sum(Gpars$slopeXclim[doSpp,]*climate[1:5])*u # climate-size 
> interaction effects|
>
> @pbadler <https://github.com/pbadler> Does this look good/right to you?
> Specifically the interactions between climate and size:
> |sum(Gpars$slopeXclim[doSpp,]*climate[1:5])*u|
>
> and the interaction between climate and crowding:
> |(W*Gpars$nbXsize)*u|
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/atredennick/MicroMesoForecast/issues/16#issuecomment-102702872>.
>

-- 
Peter Adler
Department of Wildland Resources and the Ecology Center
Utah State University
http://www.cnr.usu.edu/htm/facstaff/adler-web

**Comment by atredennick** [comment]
Yep, good catch. Fixing that now.

**Comment by atredennick** [comment]
Sort of getting around this issue by running numerical sensitivity analysis -- this way we don't have to struggle to understand the individual coefficient effects. We can focus on the emergent sensitivity of each vital rate to climate variables.
