### ISSUE TITLE
removing quad years

### ISSUE THREAD

**Issue by atredennick** [atredennick/MicroMesoForecast#7]
Chengjin removed certain quad-year combinations, like this:

`tmp2 <- which(growD$quad=="A12" & growD$year==44)`
`tmp3 <- which(growD$quad=="B1"  & growD$year==44)`
`tmp41 <- which(growD$quad=="E4" & growD$year==33)`
`tmp42 <- which(growD$quad=="E4" & growD$year==34)`
`tmp43 <- which(growD$quad=="E4" & growD$year==43)`
`tmp44 <- which(growD$quad=="E4" & growD$year==44)`

I recall asking him about this and he said these came from basically running a PCA (or NMDS or something) and these were "outliers." This is just for the BOGR data. And, some of these, like B1-1944, are ones we already removed. In this list above, only E4-43 and A12-44 *are not* removed by our fishy BOGR filter.

@pbadler Should we keep this bit in the scripts and remove the extra ones identified by Chengjin, or should we just assume that our filtering of the BOGR data is sufficient?

**Comment by pbadler** [comment]
That PCA was relevant to the multispecies models, I don' think we need 
to worry about this.

On 4/22/2015 7:53 AM, Andrew Tredennick wrote:
>
> Chengjin removed certain quad-year combinations, like this:
>
> |tmp2 <- which(growD$quad=="A12" & growD$year==44)|
> |tmp3 <- which(growD$quad=="B1" & growD$year==44)|
> |tmp41 <- which(growD$quad=="E4" & growD$year==33)|
> |tmp42 <- which(growD$quad=="E4" & growD$year==34)|
> |tmp43 <- which(growD$quad=="E4" & growD$year==43)|
> |tmp44 <- which(growD$quad=="E4" & growD$year==44)|
>
> I recall asking him about this and he said these came from basically 
> running a PCA (or NMDS or something) and these were "outliers." This 
> is just for the BOGR data. And, some of these, like B1-1944, are ones 
> we already removed. In this list above, only E4-43 and A12-44 /are 
> not/ removed by our fishy BOGR filter.
>
> @pbadler <https://github.com/pbadler> Should we keep this bit in the 
> scripts and remove the extra ones identified by Chengjin, or should we 
> just assume that our filtering of the BOGR data is sufficient?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/atredennick/MicroMesoForecast/issues/7>.
>

-- 
Peter Adler
Dept. Wildland Resources and the Ecology Center
Utah State University
http://www.cnr.usu.edu/htm/facstaff/adler-web
